---
title: "03_enet_PF_comp_SFig"
author: "Heather Wheeler"
date: "`r Sys.time()`"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(data.table)
library(viridis)
library(tidyr)
library(cowplot)
library(GGally)
"%&%" = function(a,b) paste(a,b,sep="")
my.dir = "/home/lauren/files_for_revisions_plosgen/compare_nk_samplesize/"
```


## ENET R2 range of PFs
```{r,fig.width=8,fig.height=3}
res <- fread(my.dir %&% "all_mesa_R2_different_peers.txt")

afa <- select(res, starts_with('afa')) %>% mutate(pop="AFA")
colnames(afa) <- c("PF0","PF10","PF20","PF30","pop") 
afa <- mutate(afa, PF0=ifelse(PF0<0,0,PF0), PF10=ifelse(PF10<0,0,PF10), PF20=ifelse(PF20<0,0,PF20),
              PF30=ifelse(PF30<0,0,PF30))

cau <- select(res, starts_with('cau')) %>% mutate(pop="CAU")
colnames(cau) <- c("PF0","PF10","PF20","PF30","pop") 
cau <- mutate(cau, PF0=ifelse(PF0<0,0,PF0), PF10=ifelse(PF10<0,0,PF10), PF20=ifelse(PF20<0,0,PF20),
              PF30=ifelse(PF30<0,0,PF30))

his <- select(res, starts_with('his')) %>% mutate(pop="HIS")
colnames(his) <- c("PF0","PF10","PF20","PF30","pop")
his <- mutate(his, PF0=ifelse(PF0<0,0,PF0), PF10=ifelse(PF10<0,0,PF10), PF20=ifelse(PF20<0,0,PF20),
              PF30=ifelse(PF30<0,0,PF30))

all <- rbind(afa,cau,his)

a <- ggplot(all,aes(x=PF10,y=PF0)) + geom_point(shape=1) + facet_wrap(~pop) + theme_bw(14) + labs(x=expression(paste(R^2,' with 10 PEER Factors')),y=expression(paste(R^2,' with 0 PEER Factors'))) +
  geom_abline(slope=1,intercept=0,col='blue')

b <- ggplot(all,aes(x=PF10,y=PF20)) + geom_point(shape=1) + facet_wrap(~pop) + theme_bw(14) +labs(x=expression(paste(R^2,' with 10 PEER Factors')),y=expression(paste(R^2,' with 20 PEER Factors'))) +
  geom_abline(slope=1,intercept=0,col='blue')

c <- ggplot(all,aes(x=PF10,y=PF30)) + geom_point(shape=1) + facet_wrap(~pop) + theme_bw(14) +labs(x=expression(paste(R^2,' with 10 PEER Factors')),y=expression(paste(R^2,' with 30 PEER Factors'))) +
  geom_abline(slope=1,intercept=0,col='blue')
```

```{r}
ggplot(all,aes(x=PF10,y=PF0)) + geom_point(shape=1) +  theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')

ggplot(all,aes(x=PF10,y=PF20)) + geom_point(shape=1) + theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')

ggplot(all,aes(x=PF10,y=PF30)) + geom_point(shape=1) + theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')

##his file
hisfile <- fread(my.dir %&% "his_R2_different_peers.txt")
ggplot(hisfile,aes(x=R2_10,y=R2_0)) + geom_point(shape=1) +  theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')

ggplot(hisfile,aes(x=R2_10,y=R2_20)) + geom_point(shape=1) + theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')

ggplot(hisfile,aes(x=R2_10,y=R2_30)) + geom_point(shape=1) + theme_bw(14) +
  geom_abline(slope=1,intercept=0,col='blue')
```

## S5 Fig
```{r,fig.width=8,fig.height=9}
grid.arrange(a,b,c)
```